<?php

namespace app\controllers\api;

use app\components\ChannelManage;
use app\components\Result;
use app\components\Secure;
use app\components\Telegram;
use Yii;
use yii\web\Controller;

class ChannelController extends Controller
{
	public $enableCsrfValidation = false;
	
	public function beforeAction($action)
	{
		header('Content-Type: application/json;Connection:close');
		
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionPreAdd()
	{
		$bot = Telegram::getActiveBot();
		
		$result['bot']['id']       = $bot->id;
		$result['bot']['username'] = $bot->username;
		
		Result::success($result);
	}
	
	
	public function actionAdd()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$name         = $request->post('name', '');
		$title        = $request->post('title', '');
		$join_link    = $request->post('join_link', '');
		$description  = $request->post('description', '');
		$category_id  = $request->post('category_id', '');
		$bot_id       = $request->post('bot_id', '');
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $category_id);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::add($telegram_id, $access_token, $channel_id, $name, $title,
			$description, $category_id, $bot_id, $join_link);
		
		Result::success($result);
	}
	
	public function actionInfo()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::Info($telegram_id, $access_token, $channel_id);
		
		Result::success($result);
	}
	
	public function actionEditInfo()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$title        = $request->post('title', '');
		$join_link    = $request->post('join_link', '');
		$description  = $request->post('description', '');
		$category_id  = $request->post('category_id', '');
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $category_id);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::editInfo($telegram_id, $access_token, $channel_id,
			$title, $description, $category_id, $join_link);
		
		Result::success($result);
	}
	
	public function actionParticipate()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$at_1         = $request->post('at_1', 0);
		$at_2         = $request->post('at_2', 0);
		$at_3         = $request->post('at_3', 0);
		$at_4         = $request->post('at_4', 0);
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $at_1 + $at_2 + $at_3 + $at_4);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::participate($telegram_id, $access_token, $channel_id,
			$at_1, $at_2, $at_3, $at_4);
		
		Result::success($result);
	}
	
	public function actionSpecialExchangeRequest()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$target_group = $request->post('target_group', '');
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $target_group);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::specialExchangeRequest($telegram_id, $access_token, $channel_id,
			$target_group);
		
		Result::success($result);
	}
	
	public function actionGroupStatus()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		
		$result = ChannelManage::groupStatus();
		
		Result::success($result);
	}
	
	public function actionGetExchangeCount()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::getExchangeCount($telegram_id, $access_token, $channel_id);
		
		Result::success($result);
	}
	
	public function actionSetBot()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$bot_id       = $request->post('bot_id', '');
		$agent        = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::setBot($telegram_id, $access_token, $channel_id, $bot_id);
		
		Result::success($result);
	}
	
	public function actionExchangeList()
	{
		$request = Yii::$app->request;
		
		$telegram_id = $request->post('telegram_id', '');
		$at          = $request->post('at', '');
		$channel_id  = $request->post('channel_id', '');
		$page_number = $request->post('page_number', '');
		$per_page    = $request->post('per_page', '');
		$agent       = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $page_number + $per_page);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::exchangeList($telegram_id, $at, $channel_id, $page_number, $per_page);
		
		Result::success($result);
	}
	
	public function actionExchangeParticipantsList()
	{
		$request = Yii::$app->request;
		
		$telegram_id = $request->post('telegram_id', '');
		$at          = $request->post('at', '');
		$exchange_id = $request->post('exchange_id', '');
		$agent       = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $exchange_id);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::exchangeParticipantsList($telegram_id, $at, $exchange_id);
		
		Result::success($result);
	}
	
	public function actionSpecialExchangeList()
	{
		$request = Yii::$app->request;
		
		$telegram_id = $request->post('telegram_id', '');
		$at          = $request->post('at', '');
		$channel_id  = $request->post('channel_id', '');
		$page_number = $request->post('page_number', '');
		$per_page    = $request->post('per_page', '');
		$status      = $request->post('status', '');
		$agent       = $request->post('agent', '');
		
		$string = (string)(1000000000000000 + $telegram_id + $page_number + $per_page);
		Secure::Authorize($agent, $string);
		
		$result = ChannelManage::specialExchangeList($telegram_id, $at, $channel_id, $status, $page_number, $per_page);
		
		Result::success($result);
	}
	
	public static function actionViolationReport()
	{
		$request = Yii::$app->request;
		
		$telegram_id  = $request->post('telegram_id', '');
		$access_token = $request->post('at', '');
		$channel_id   = $request->post('channel_id', '');
		$exchange_id  = $request->post('exchange_id', '');
		$type         = $request->post('type', '');
		$description  = $request->post('description', '');
		$agent        = $request->post('agent', '');
		/*
		$string = (string)(1000000000000000 + $telegram_id + $exchange_id + $type);
		Secure::Authorize($agent, $string);*/
		
		$result = ChannelManage::violationReport($telegram_id, $access_token, $channel_id, $exchange_id, $type, $description);
		
		Result::success($result);
	}
	
}
