<?php

namespace app\controllers\api;

use app\components\LocationManager;
use app\components\MCrypt;
use app\components\Result;
use app\components\Secure;
use app\components\UserManage;
use app\models\Area;
use Yii;
use yii\web\Controller;

class HelperController extends Controller
{
	public $enableCsrfValidation = false;
	
	public function beforeAction($action)
	{
		header('Content-Type: application/json;Connection:close');
		
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	/*
	 * Get nearest hospital or clinic center
	 */
	public function actionGetNearestCenter()
	{
		
		$lat   = $_GET['lat'];
		$long  = $_GET['long'];
		$token = $_GET['token'];
		
		$result = LocationManager::nearestCenter($lat, $long, $token);
		
		Result::success($result);
	}
	
	/*
	 * Find the nearest helper to help the user
	 */
	public function actionGetNearestHelper()
	{
		
		$lat   = $_GET['lat'];
		$long  = $_GET['long'];
		$token = $_GET['token'];
		
		$result = LocationManager::nearestHelper($lat, $long, $token);
		
		Result::success($result);
	}
	
}
