<?php

namespace app\controllers\api;


use app\components\Result;
use app\models\Notification;
use Yii;

class NotificationController extends \yii\web\Controller
{
	public $enableCsrfValidation = false;
	
	public function beforeAction($action)
	{
		header('Content-Type: application/json;Connection:close');
		
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	public function actionList()
	{
		$telegram_id  = $_POST['telegram_id'];
		$access_token = $_POST['access_token'];
		$page_number  = $_POST['page_number'];
		$per_page     = $_POST['per_page'];
		
		$result = Notification::getList($telegram_id, $access_token, $page_number, $per_page);
		
		Result::success($result);
	}
	
}
