<?php

namespace app\controllers\api;

use app\components\Result;
use app\components\SettingManage;
use Yii;
use yii\web\Controller;

class SettingController extends Controller
{
	public $enableCsrfValidation = false;
	
	public function beforeAction($action)
	{
		header('Content-Type: application/json;Connection:close');
		
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}
	
	
}
